// <auto-generated />
using System;
using Afterimage.Domain.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Afterimage.Domain.Migrations
{
    [DbContext(typeof(AfterimageDbContext))]
    partial class AfterimageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Afterimage.Domain.Photos.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("lifecycle_state");

                    b.Property<string>("OriginalStorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_storage_key");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("ThumbnailStorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("thumbnail_storage_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_photos");

                    b.HasIndex("OwnerId", "LifecycleState", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_photos_owner_id_lifecycle_state_created_at");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("Afterimage.Domain.Photos.Photo", b =>
                {
                    b.OwnsOne("Afterimage.Domain.Photos.PhotoMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("PhotoId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("Height")
                                .HasColumnType("integer");

                            b1.Property<DateTimeOffset?>("TakenAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int?>("Width")
                                .HasColumnType("integer");

                            b1.HasKey("PhotoId");

                            b1.ToTable("photos");

                            b1.ToJson("metadata");

                            b1.WithOwner()
                                .HasForeignKey("PhotoId")
                                .HasConstraintName("fk_photos_photos_id");
                        });

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
